# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_foot = QtWidgets.QLabel(self.centralwidget)
        self.label_foot.setGeometry(QtCore.QRect(0, 540, 71, 20))
        self.label_foot.setObjectName("label_foot")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(280, 310, 511, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 491, 171))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.textEdit.setPalette(palette)
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.textEdit.setObjectName("textEdit")
        self.bt_test_2 = QtWidgets.QPushButton(self.groupBox)
        self.bt_test_2.setGeometry(QtCore.QRect(420, 200, 81, 31))
        self.bt_test_2.setObjectName("bt_test_2")
        self.bt_test = QtWidgets.QPushButton(self.groupBox)
        self.bt_test.setGeometry(QtCore.QRect(10, 200, 81, 31))
        self.bt_test.setCheckable(False)
        self.bt_test.setObjectName("bt_test")
        self.bt_3_link = QtWidgets.QPushButton(self.centralwidget)
        self.bt_3_link.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.bt_3_link.setCheckable(False)
        self.bt_3_link.setObjectName("bt_3_link")
        self.bt_4_begin = QtWidgets.QPushButton(self.centralwidget)
        self.bt_4_begin.setGeometry(QtCore.QRect(20, 500, 81, 31))
        self.bt_4_begin.setCheckable(False)
        self.bt_4_begin.setObjectName("bt_4_begin")
        self.label_3_link = QtWidgets.QLabel(self.centralwidget)
        self.label_3_link.setGeometry(QtCore.QRect(110, 30, 71, 20))
        self.label_3_link.setObjectName("label_3_link")
        self.label_4_begin = QtWidgets.QLabel(self.centralwidget)
        self.label_4_begin.setGeometry(QtCore.QRect(110, 510, 71, 20))
        self.label_4_begin.setObjectName("label_4_begin")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 10, 511, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.te_2_send = QtWidgets.QTextEdit(self.groupBox_2)
        self.te_2_send.setGeometry(QtCore.QRect(10, 20, 491, 201))
        self.te_2_send.setTabStopWidth(20)
        self.te_2_send.setTabStopDistance(20.0)
        self.te_2_send.setPlaceholderText("")
        self.te_2_send.setObjectName("te_2_send")
        self.bt_5_send = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_5_send.setGeometry(QtCore.QRect(420, 230, 81, 31))
        self.bt_5_send.setCheckable(False)
        self.bt_5_send.setObjectName("bt_5_send")
        self.bt_6_rfctrl = QtWidgets.QPushButton(self.groupBox_2)
        self.bt_6_rfctrl.setGeometry(QtCore.QRect(10, 230, 81, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 204, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.bt_6_rfctrl.setPalette(palette)
        self.bt_6_rfctrl.setCheckable(False)
        self.bt_6_rfctrl.setObjectName("bt_6_rfctrl")
        self.bt_7_link_smf = QtWidgets.QPushButton(self.centralwidget)
        self.bt_7_link_smf.setGeometry(QtCore.QRect(20, 70, 81, 31))
        self.bt_7_link_smf.setCheckable(False)
        self.bt_7_link_smf.setObjectName("bt_7_link_smf")
        self.bt_8_link_fsw = QtWidgets.QPushButton(self.centralwidget)
        self.bt_8_link_fsw.setGeometry(QtCore.QRect(20, 120, 81, 31))
        self.bt_8_link_fsw.setCheckable(False)
        self.bt_8_link_fsw.setObjectName("bt_8_link_fsw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(12)
        self.statusbar.setFont(font)
        self.statusbar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.bt_test.clicked.connect(MainWindow.bt_test_click)
        self.bt_test_2.clicked.connect(MainWindow.bt_test_2_click)
        self.bt_3_link.clicked.connect(MainWindow.bt_3_link_click)
        self.bt_4_begin.clicked.connect(MainWindow.bt_4_begin_click)
        self.bt_5_send.clicked.connect(MainWindow.bt_5_send_click)
        self.bt_6_rfctrl.clicked.connect(MainWindow.bt_6_rfctrl_click)
        self.bt_7_link_smf.clicked.connect(MainWindow.bt_7_link_smf_click)
        self.bt_8_link_fsw.clicked.connect(MainWindow.bt_8_lin_fsw_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_foot.setText(_translate("MainWindow", "lable_foot"))
        self.groupBox.setTitle(_translate("MainWindow", "调试信息："))
        self.bt_test_2.setText(_translate("MainWindow", "clear"))
        self.bt_test.setText(_translate("MainWindow", "test"))
        self.bt_3_link.setText(_translate("MainWindow", "连接矢网"))
        self.bt_4_begin.setText(_translate("MainWindow", "开始测试"))
        self.label_3_link.setText(_translate("MainWindow", "未连接"))
        self.label_4_begin.setText(_translate("MainWindow", "等待测试"))
        self.groupBox_2.setTitle(_translate("MainWindow", "仪表测试指令"))
        self.bt_5_send.setText(_translate("MainWindow", "发送命令"))
        self.bt_6_rfctrl.setText(_translate("MainWindow", "RF OFF"))
        self.bt_7_link_smf.setText(_translate("MainWindow", "连接信号源"))
        self.bt_8_link_fsw.setText(_translate("MainWindow", "连接频谱仪"))
